### ISSUE TITLE
As an official, I want to be able to set an opening time for hearing to be published, and look at it as draft before it is public

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#119]

**Comment by akx** [comment]
A partial implementation of this landed in https://github.com/City-of-Helsinki/kerrokantasi/pull/106 (specifically https://github.com/akx/kerrokantasi/commit/42b956a78d544d295c3db297843887b961856bb6 and https://github.com/akx/kerrokantasi/commit/2e3710e31ed6fff982a5a963297c30b961f67c24) however the semantics regarding the force-closed flag (`closed`) are not yet clear, so I'll work on that.
