### ISSUE TITLE
Bring user experience to same level as the old service, both desktop and mobile

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#132]
The current version is available at https://kerrokantasi.hel.fi/

The new UX should be equivalent or better, and responsive to boot.

**Comment by Rikuoja** [comment]
Hearing tags should be visible.

**Comment by Rikuoja** [comment]
Front page needs polishing and pictures visible.

**Comment by Rikuoja** [comment]
Consider font selection, heading styles etc.

**Comment by Rikuoja** [comment]
Show section picture thumbnails, before clicking on a section.

**Comment by Rikuoja** [comment]
On the left column, spacing between hearing section headers and numbers.

**Comment by Rikuoja** [comment]
Remove redundant "Kartta" heading, move social media sharing buttons above the map for increased visibility?

**Comment by akx** [comment]
The changes this issue concerned landed in #148, #149, #150, #151.

Any further changes should be made via new issues for clarity.
