### ISSUE TITLE
When adding a comment, reload comments and scroll to display the latest comment

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#174]

**Comment by Rikuoja** [comment]
Currently the comment is not shown when posted, and the written text remains in the textbox. This results in people posting the same comment multiple times, expecting to get visual feedback.

**Comment by JsseL** [comment]
Partial fix for the problem. Will implement the scroll to latest comment feature later.

**Comment by Rikuoja** [comment]
If the latest comment is displayed first, no scrolling is needed. Currently, the comment is appended to the end of the list so it is not displayed?

**Comment by JsseL** [comment]
Yep, currently shown in the bottom.
