### ISSUE TITLE
times should be shown in local times

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#185]
when user is adding a hearing, the starting and closing times are shown in "server time" with a text explanation that "You are 3 hours ahead of server time". This should be fixed so that the user is shown times in Helsinki time and no explanations are needed.

![image](https://cloud.githubusercontent.com/assets/2391876/14341343/b4b9cf26-fc99-11e5-9fc2-46d6a7b80910.png)

**Comment by Rikuoja** [comment]
Backend admin issue.
