### ISSUE TITLE
changing "order" does not work

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#190]
the pictures appear in the same order (lower picture) even after their order number is reversed (5=>4). The order number does not seem to have any functionality.

![image](https://cloud.githubusercontent.com/assets/2391876/14342156/52e7aef6-fca0-11e5-9951-6dfa3a613a0c.png)

![image](https://cloud.githubusercontent.com/assets/2391876/14342165/65c8a25a-fca0-11e5-84d9-a26056a6b84a.png)

**Comment by Rikuoja** [comment]
Duplicate of #187 , skip ordering or make it count. Preferably, a more flexible (flexbox style) image placement method needed.
