### ISSUE TITLE
tryng to delete a section image causes 500 error

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#191]
when i try to delete a section image of a hearing (http://api.hel.fi/kerrokantasi/admin/democracy/hearing/uudet_5Fasunnot/change/) i get a 500 error.

![image](https://cloud.githubusercontent.com/assets/2391876/14342224/d0feb4b0-fca0-11e5-9c1b-10e0f45fb879.png)

![image](https://cloud.githubusercontent.com/assets/2391876/14342235/e0923744-fca0-11e5-9c88-ec0cbec476cd.png)

**Comment by Rikuoja** [comment]
Backend admin issue.
