### ISSUE TITLE
make a new UI element for the public servant contact info

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#195]
the contact info of the people at the city is standard content for each hearing. should we move this to the left column in a separate element? on a small screen it could drop to the very bottom of the screen below the comments?

![image](https://cloud.githubusercontent.com/assets/2391876/14350283/2fd04348-fcd1-11e5-92c0-40b85afe76ef.png)

**Comment by Rikuoja** [comment]
+1, or, yes we should. On the issue list for the backend is already an obligatory separate field for the contact info.
