### ISSUE TITLE
Prevent accidental scrolling and zooming of hearing map outside the hearing area

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#204]

**Comment by JsseL** [comment]
So #207 would fix this. After trying it in action, I'm not sure if it actually makes the map more user friendly. Leaflet's max bounds implementation feel a bit glitchy and it also felt a bit too restricting.

I tried to make it a bit more user friendly by setting the max bounds a bit wider than the hearing area itself. This way user is able to pan the viewport a bit wider than just the border of the hearing area. Increasing the max bounds even more could make it even more usable, but eventually it would lead to the original problem.

I think you should try it out and see how it feels in action.

**Comment by JsseL** [comment]
Updated the PR. Now it should actually improve the UX of the map element.
