### ISSUE TITLE
As a resident or official I want to be able to log in with my email-account and password.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#21]

**Comment by rambo** [comment]
As in using email address as account name or as in using OAuth (or SAML2) if their email provider provides it ?

**Comment by joonasp** [comment]
allow people to create a specific account (email & password) on this service (for those who can't or do not want to sign in directly with oAuth).

**Comment by akx** [comment]
Dropping out, using HEL SSO

**Comment by Rikuoja** [comment]
Not going to implement
