### ISSUE TITLE
When hearing is not yet open, do not display "hearing is closed" message in the UI

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#210]

**Comment by JsseL** [comment]
So currently hearing is reagarded as "closed" according to this rule: `self.force_closed or not (self.open_at <= now() <= self.close_at)`.

This means all hearing that have their `open_at` in the future are regarded as "closed". Is that correct logic? UI is just representing that information so it works pretty much as it should. Though the wording might be for example "suljettu" in stead of "sulkeutunut".

Also: AFAIK API doesn't return hearings which will open in future anymore.

### Conclusion
I don't see any action required.

**Comment by Rikuoja** [comment]
The API will return those hearings for admins who are creating the hearing. Therefore, the box should not be rendered if the opening date is in the future.

**Comment by jonnetanninen** [comment]
This seems to be a backend issue. The UI checks from the response key "closed" if the hearing is closed. Now it seems to return true in this case here. Of course we can check "if (closed && published)" in the UI if the closed message should be displayed, but I suggest this is fixed in the backend instead.

**Comment by Rikuoja** [comment]
Well, the problem is that `closed` in the API indeed means that the hearing cannot be commented on. It doesn't mean the hearing is in the past; it just means the hearing is not available for commenting. If i changed it in the backend, lots of the UI would break down in strange ways, because all of a sudden future hearings wouldn't be closed anymore.

`closed` in the backend does not mean the same as "Kuuleminen on suljettu eikä enää vastaanota kommentteja" in the UI. This text should not be displayed for all hearings with status `closed`; but only those that have been published and have been open in the past.

**Comment by jonnetanninen** [comment]
Ok so this is indeed an UI issue then and shall be fixed :)

**Comment by Rikuoja** [comment]
Fixed in #445
