### ISSUE TITLE
As a resident or official I want to be able to read instructions to change my password, if I have lost or forgotten it.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#22]

**Comment by itimo** [comment]
User writes email to form and receives instructions to change password. Isntructions include link to reset password without knowing the old one. After click user is automatically logged in.

**Comment by akx** [comment]
This is actually invalid, since there are no local accounts for Kerro Kantasi; everything is done via https://github.com/City-of-Helsinki/django-helusers' OAuth API.
