### ISSUE TITLE
IE11: scrolling causes top menu to appear and disappear

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/kerrokantasi-ui#220]
Problem: While scrolling using IE11 the top menu toggles in and out of existence.

Expected behaviour: menu bar shrinks when starting to scroll from top and stays minified but visible thereafter

Platform: IE11 on Windows 7 (modern.ie virtual machine)

**Comment by Rikuoja** [comment]
Probably linked to #409 .

**Comment by Rikuoja** [comment]
Oops, not closed.

**Comment by Rikuoja** [comment]
Duplicate of #409.
