### ISSUE TITLE
Resize comment box to fit a longer comment.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#223]
Currently, writing longer comments is very difficult as only few lines are visible at the same time.

**Comment by vaaralav** [comment]
@Rikuoja does this issue require dynamic height for the comment box or is it enough to just make the `<textarea>` higher eg. fitting 8 rows?

**Comment by Rikuoja** [comment]
@vaaralav Hm, there seems to be a control for heightening the box. Is it possible to have a height of four rows and then actually extending it dynamically? If dynamic height is not easy, I think four or six rows should suffice for most comments.
