### ISSUE TITLE
Enable switching UI language

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#230]
Display hearing in selected language if available.

**Comment by Rikuoja** [comment]
Display all Comments and Hearings regardless of language. Allow selecting UI language at the top.

1) Comments: A comment may only be in a single language. However, preferred UI language comments will be displayed first. Display Comments in other languages below the preferred language comments. Comments not in the preferred language will be displayed slightly faded.

2) Hearing list: A hearing may be in several language. Display Hearing in preferred language if available. If it is not available, display Hearing in the hearing language (e.g. Finnish) with a slight fade effect. Hearings not in the preferred language will be displayed slightly faded.

3) Tags: Display translation if available.

4) Front page: Display the most popular Hearing available in the preferred UI language as Featured Hearing. Display all open Hearings (regardless of language) on the front page, Hearings not in the preferred language will be displayed slightly faded.

**Comment by Rikuoja** [comment]
Wireframes: https://drive.google.com/file/d/0Bx82qsGr59nCVWpJamJ3QjF6TTA/view?usp=sharing

**Comment by akx** [comment]
The commit https://github.com/City-of-Helsinki/kerrokantasi-ui/commit/c9cb13023230a072846270ef353f9f6a96af18b4 may be useful as a reference to revert to :)
