### ISSUE TITLE
Allow a full-screen mode for a Hearing with map plugin

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#251]
Such a Hearing will launch directly in full-screen map mode. The top Header should display the name of the Hearing and allow moving between Map and Info modes within the Hearing.

**Comment by Rikuoja** [comment]
The only way to get away from the Hearing is a small Kerrokantasi icon at the left of the Header. This is meant for a streamlined mobile experience of the single Hearing.

**Comment by JsseL** [comment]
Do you mean by "Info mode" the same view as hearings are normally presented with?

**Comment by Rikuoja** [comment]
Yes.

**Comment by Rikuoja** [comment]
This could be implemented e.g. by redirecting to `kerrokantasi.hel.fi/hearing/xxxx?fullscreen=true`, whenever entering `kerrokantasi.hel.fi/hearing/xxxx` and `fullscreen=true` is set for the Hearing in the backend?

Still, once the Hearing has been constructed, it should be possible to transition back into the usual Kerrokantasi view by redirecting e.g. to `kerrokantasi.hel.fi/hearing/xxxx?fullscreen=false`.

In the info page, we want to be able to embed a BIG link that takes us back to the full screen mode, hence the need for a separate URL for the full screen mode.

Also, this way the App.js will know the mode from the URL, and knows to minimize the Header bar accordingly, and will be able to show only the Hearing title in the Header?

**Comment by Rikuoja** [comment]
In such a Hearing, the plugin and CommentList should not be rendered at all in the Hearing info page.

The comments for the Hearing will be rendered in the fullscreen plugin, so the Hearing page is only for displaying Hearing text and links.
