### ISSUE TITLE
On the Hearing page, link to all available Hearing languages in the sidebar, if several languages are available.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#257]

**Comment by vaaralav** [comment]
@Rikuoja any specs for this one? What's the data structure for multilingual hearings?

**Comment by Rikuoja** [comment]
@vaaralav For all string fields in Hearings, Labels etc., instead of a string
```
"title": "Vaasanpuistikon kehittämisen viitesuunnitelma"
```
we will have an object
```
"title": {
"fi": "Vaasanpuistikon kehittämisen viitesuunnitelma",
"sv": "Samma på svenska",
"en": "Same in English"}
```

**Comment by Rikuoja** [comment]
What I would do is just check the `title` for languages that are present and display languages accordingly. There might be some missing fields in some of the languages, but we will most likely not have a separate field indicating which languages are present, as this would not prevent translations being missing anyway.

**Comment by Rikuoja** [comment]
Hence, we will always have to fall back to another language if data in the given language is missing or empty.

**Comment by vaaralav** [comment]
I'm guessing this means switching the language for whole hearing including abstract, questions, etc. How this should be implemented in the sidebar? Replace "Kuuleminen" with 
- Vaasanpuistikon kehittämisen viitesuunnitelma
- Samma på svenska
- Same in English ?
<img width="308" alt="screen shot 2016-12-16 at 15 11 04" src="https://cloud.githubusercontent.com/assets/8571541/21263936/2a91f12c-c3a2-11e6-90f9-794e6c04f8a7.png">

**Comment by vaaralav** [comment]
And have I understood correctly that selecting the hearing language shouldn't change UI language? It would be easier to implement by making another language chooser to the sidebar with the translated hearing titles :)

**Comment by Rikuoja** [comment]
Yes, the Hearing language shouldn't affect the UI language. The other way around, on the other hand, changing the UI language should render the Hearing in that language if it is available.

In the sidebar, I would make a separate element for selecting the language (only if several languages are available), as in https://drive.google.com/file/d/0Bx82qsGr59nCVWpJamJ3QjF6TTA/view . Then, all the Hearing content (including Sidebar headers) would only be shown in that language.

**Comment by Rikuoja** [comment]
![image](https://cloud.githubusercontent.com/assets/9367712/21264245/eba953b8-c3a3-11e6-86b4-8033765964de.png)

**Comment by vaaralav** [comment]
@Rikuoja changing the language for headers translated with `react-intl` seems to be impossible. At least I haven't found a way to override the locale for `FormattedMessage` components. Hearing attributes retrieved from API can be translated with ease when changing the language for Hearing view.
