### ISSUE TITLE
As a resident or official I want to change my email-account in service.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#26]

**Comment by itimo** [comment]
New email account receives confirmation email, which includes link to confirm account. Old email account is active untill confirmation is completed.

**Comment by rambo** [comment]
Officials already can use the citys SSO service, I think we should use that as a source of canonical email address. It might be useful to be able to specify a separate email on the service level though but then the user will have to change their email in multiple places.

**Comment by joonasp** [comment]
allow updating email only for residents at this point.

**Comment by Rikuoja** [comment]
Tunnistamo deals with this.
