### ISSUE TITLE
Allow creating contact persons in admin UI

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#276]

**Comment by Rikuoja** [comment]
Requires frontend #240

**Comment by vaaralav** [comment]
@Rikuoja seems like the backend for this is not done yet? https://github.com/City-of-Helsinki/kerrokantasi/issues/240

**Comment by Rikuoja** [comment]
Nope it is not :) However, the data is just the contact person JSON as is, with all fields required (apart from ID).

**Comment by Rikuoja** [comment]
Now implemented in the test API, go ahead and try it :)

**Comment by Rikuoja** [comment]
Also, the contact person JSON now contains the title in several languages, so the title will have to be posted as an object in the JSON.
