### ISSUE TITLE
As an official I want to be able to remove hearing which I have created.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#28]

**Comment by itimo** [comment]
Confirmation of removal should be implemented so that user must rewrite a heading of hearing again. There lies couple of design problems: What does confirmation look like? Where is remove button?

**Comment by rambo** [comment]
As with all removals the objects must not be deleted from the database, just flagged as deleted so they can be restored later if needed. 

The modern way anyway is to just do what the user asks and then offer "undo" in the message that tells that the object was deleted.

**Comment by joonasp** [comment]
let's make it three stage:
"delete" button leads to a confirmation dialgogue asking  "Are you sure you want to delete this hearing?". Clicking Yes shows a message saying that that hearing is now deleted, and restoring it requires contacting tech support, and still give the "undo" button at this stage.
