### ISSUE TITLE
Update react-router & al.

### ISSUE THREAD

**Issue by vaaralav** [City-of-Helsinki/kerrokantasi-ui#290]
The currently used version (1.0.0-rc3) is ancient. Someone with knowledge of SSR should do the update as updating breaks compatibility with eg. `redux-router`.

**Comment by vaaralav** [comment]
These warnings are related to the old version of `react-router`:
```
You are manually calling a React.PropTypes validation function for the `path` prop on `Route`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```
Also see discussion https://github.com/ReactTraining/react-router/issues/3988#issuecomment-250982076

**Comment by Rikuoja** [comment]
Oh and there are a dozen other dependencies that are just as ancient, so they should be updated too.

**Comment by akx** [comment]
A baker's dozen...

```
~/b/kerrokantasi-ui (master *+) $ npm outdated | wc -l
      84
```

**Comment by Rikuoja** [comment]
What's a factor of seven between friends?

**Comment by Rikuoja** [comment]
Do-one.
