### ISSUE TITLE
Refactor admin UI to function with multiple language backend

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#303]

**Comment by Rikuoja** [comment]
Only Finnish texts need to be accessed, for now.

**Comment by vaaralav** [comment]
## AdminHearings - `/admin`

- [ ] Refactor fetching with labels and search phrase
- [ ] Use `isLoading` per hearing list tab (Julkiset / Julkaisujono / Luonnokset)

## Manage - `/admin/manage`

- [ ] Todo

**Comment by vaaralav** [comment]
> Similar to linkedevents.hel.fi UI, add check boxes allowing the user to add desired languages to the Hearing.

@Rikuoja any screenshot for this as I'm not familiar with LinkedEvents? Also, any spec what kind of requests API supports for hearings with multiple languages?

**Comment by Rikuoja** [comment]
Ah, 1) 
![image](https://cloud.githubusercontent.com/assets/9367712/25125390/f704187e-242e-11e7-8a2b-76b1fc864748.png)

This will require some specifying as to what to do when the user actually selects several languages in the checkbox. In Linkedevents, what happens is that each multilanguage field then actually displays text fields for each of the selected languages, as pictured. This is probably the safest bet, because all the other fields should be common in all languages.

2) The multiple language API is deployed on https://api.hel.fi/kerrokantasi-test/v1/hearing/ . Essentially, all the multilanguage fields will just be objects with language codes, instead of plain strings.

**Comment by Rikuoja** [comment]
In the current implementation, the UI decided what languages to display the hearing in by checking the language objects present in the title field. Then, if other fields in that language are missing, they are just rendered empty.

**Comment by Rikuoja** [comment]
I would say this is by now satisfyingly implemented.
