### ISSUE TITLE
Add frontend validation for fields in the admin UI

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#304]

**Comment by vaaralav** [comment]
@Rikuoja any spec for this one? Some API documentation would do also ;)

**Comment by Rikuoja** [comment]
Eh, I'll do my best. The following validation rules should do:

- at least one language must be selected
- the title must not be empty
- the slug must only allow valid slug letters, probably prevent inserting invalid letters in the first case
- there must be at least one tag
- there must be at least one contact person
- there must be a main section, and it must have an image, caption, abstract and content
- there must be opening and closing times, and they must be in the future

**Comment by Rikuoja** [comment]
However, for actually saving a hearing to be published later, these validations should not be run. They should only be run when clicking the "Publish" button.

This means that when clicking "Publish", we should run all the validations and open the editor form displaying all the errors.

For creating non-finished non-public hearings, a subset of these validations (at least one language, plus a name) should do. I'll fix the backend so that non-finished hearings can be saved without further data.

**Comment by Rikuoja** [comment]
However, all the required fields should be indicated with a star on the form. This way, the requirement for these fields to be filled before publication should be obvious, even though we can save a draft with some data missing.

**Comment by Rikuoja** [comment]
This is implemented for the most part already, don't know if we will need the rest of the specified functionality at all.
