### ISSUE TITLE
Show "Hearing not found" message when API returns 404 for hearing

### ISSUE THREAD

**Issue by vaaralav** [City-of-Helsinki/kerrokantasi-ui#316]
Current behaviour:
<img width="1411" alt="screen shot 2017-04-18 at 17 37 58" src="https://cloud.githubusercontent.com/assets/8571541/25126868/e0a9511e-245d-11e7-85e6-e5f6f38c4a2d.png">

When API returns 404, the spinner should be replaced with some kind of 404 page.

**Comment by Rikuoja** [comment]
Fixed in #445
