### ISSUE TITLE
When a hearing is published, add a button for making hearing non-public

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#337]
Needed in emergencies where e.g. it contains data that should not have been published yet, or needs to be revised before it can be published again.

**Comment by Rikuoja** [comment]
Next to "Sulje kuuleminen". Name the button "Peru julkaisu"?

**Comment by jonraem** [comment]
Yes!

**Comment by Rikuoja** [comment]
Fixed in #369
