### ISSUE TITLE
As an official I want to be able to choose map of the area, which concerns the hearing.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#34]

**Comment by itimo** [comment]
Given in list of coordinates.

**Comment by rambo** [comment]
The officials definitely do not want to give a list of coordinates, see http://leaflet.github.io/Leaflet.draw/

**Comment by joonasp** [comment]
@juyrjola had a tool in mind to allow the official to easily draw a polygon on the map.

**Comment by juyrjola** [comment]
Right, Leaflet.draw is already linked to above.
