### ISSUE TITLE
Fix hearing section browser components on mobile

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#342]

**Comment by Rikuoja** [comment]
![image](https://user-images.githubusercontent.com/9367712/27916217-1a96700e-6271-11e7-89a8-2caafcac0054.png)

**Comment by Rikuoja** [comment]
Fixed in #375

**Comment by terotic** [comment]
Actually fixed in #365 👯‍♂️ 
My bad!
