### ISSUE TITLE
Show sidebar map only if the hearing is location based

### ISSUE THREAD

**Issue by terotic** [City-of-Helsinki/kerrokantasi-ui#363]
Hide sidebar map on hearings that are not related to specific area or location.

**Comment by Rikuoja** [comment]
I think it is hidden already? It only appears if a geometry is present in the hearing.

Sadly, there is nothing stopping people to making hearings with very large (Helsinki-wide) areas, which will then show on the map.

**Comment by terotic** [comment]
True. So this is user-related problem.
