### ISSUE TITLE
As an official I want to be able to edit the abstract of introduction or scenario.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#38]

**Comment by piotras** [comment]
What is 'element' ?

**Comment by itimo** [comment]
It is an introduction to hearing (e.g. https://kerrokantasi.hel.fi/meilahdenkoulut) or introduction to scenario of that hearing (see "Vaihtoehto" 1, 2 and 3 at the bottom of that page). 

I agree, "element" is not correct translation here. We should probably change it to "text section" or something more suitable in order to avoid misunderstandings.
