### ISSUE TITLE
Add sentry integration instead of alertifying the user of JS errors

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#381]

**Comment by jonnetanninen** [comment]
Do we still want to alertify some general message for the user if something fails?

**Comment by Rikuoja** [comment]
Hmm, I would say a general Finnish message along the lines of "Something went wrong. We sent an error report to the developers."

**Comment by jussiarpalahti** [comment]
Well, as my original #324 stated, there's already feedback form provided by Sentry which might be useful. Then again, it might not.

**Comment by jonnetanninen** [comment]
Is something like "Something went wrong. Try again soon or refresh your browser." ok as this will usually solve the problem for the user?

**Comment by Rikuoja** [comment]
That sounds sensible. Reloading fixes the most common reason of these problems, which is expiration of the oauth token.

**Comment by Rikuoja** [comment]
Implemented in #432, absent actual integration to deployment.
