### ISSUE TITLE
As an official I want to be able to edit the body text of text section (introduction or scenario).

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#39]

**Comment by rambo** [comment]
With rich formatting (so a HTML editor widget [inline editing is one too]).

**Comment by joonasp** [comment]
We only want to provide a limited set of formatting options (at this stage: bold, underline, italic, hyperlink, heading style) but as a WYSIWYG editor that is easy to use for officials that are used to using MS word, etc. in their everyday work...
