### ISSUE TITLE
Do not render comments section if commenting is disabled or there are no comments yet

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#390]

**Comment by jonnetanninen** [comment]
1. The commenting form is rendered inside comment section so I guess we still want to render it even though there are no comments yet?

2. Do we still want to render existing comments if the commenting has been disabled?

**Comment by Rikuoja** [comment]
1) Yes, the form should be displayed if commenting is allowed, but not the empty headline below it.

2) Yes, the headline and comments should be displayed whenever there are comments, but not the form is commenting is not (or no longer) allowed.

I guess previous coding messed this up somewhat, that's why the headline appears even if no comments are present.
