### ISSUE TITLE
Compactify the footer

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#399]
Currently scrolling to the bottom of the hearing is a funny experience as the black box obscures most of the screen.

![image](https://user-images.githubusercontent.com/9367712/29304967-c0c05c64-819e-11e7-9fd5-c7ab36f30041.png)

**Comment by petterill** [comment]
Raise Rekisteriseloste, Palaute and Heslingin kaupunki up, and cut out the rest

**Comment by terotic** [comment]
We do not have the sidebar on the hearings anymore so this issue is not really valid anymore. Footer fine as it is for now.
