### ISSUE TITLE
As a user I want to be able to choose languages between Finnish, Swedish and English.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#4]

**Comment by piotras** [comment]
Is this related to navigation localization only? I wonder if backend should be language aware or just serve content as is.

**Comment by rambo** [comment]
Backend needs to be language-aware, the hearings must have translatable content. Apparently http://django-modeltranslation.readthedocs.org/en/latest/ is a good choice for that.

It's probably good idea to tag the language that was selected when the comment was saved to the comment as well (the metadata might be usefull) but I do not think we want to filter comments by language

**Comment by vikoivun** [comment]
This has been done and published. Both UI itself and the hearings support multiple languages.
