### ISSUE TITLE
Allow hearing editor to create paragraphs with custom classes (e.g. lead)

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#401]
Currently, draft.js doesn't support this. Would require forking draft.js and rewriting https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js

**Comment by Rikuoja** [comment]
Probably not worth it, even though such paragraphs are present in current hearings.

In the mean time, bolded or otherwise emphasized text formatting should be considered, or perhaps introduce another way of structuring hearing text to separate the chapters to be rendered in `lead` style?

**Comment by Rikuoja** [comment]
Obviously, we do have access to the bare HTML, so we could do a hack around draft.js wherein we separately sniff for any `<p class='lead'>` tags and try to save them pointing to the right draft.js generated block, perhaps matching the block by text content?

**Comment by jonnetanninen** [comment]
I'm pretty sure this can be accomplished with draft.js.

The question is, do we want to support any custom class or is supporting lead enough?

**Comment by Rikuoja** [comment]
I would say lead is enough.

We really don't want to support any other formatting than strictly necessary, to retain uniform look across all kerrokantasi hearings; this is basically the only custom class present in hearings.

**Comment by Rikuoja** [comment]
Fixed.
