### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#405]
As Riku, I want the server side rendering to work on the server, not just in development. As end user, I want to share hearings so that picture and other data are available in the facebook share.

**Comment by akx** [comment]
If it works in development, the only difference can only be in deployment and configuration. Is the `serverRendering` configuration option enabled?

**Comment by vikoivun** [comment]
Indeed it was. It created an odd half created page, with parts missing. Ghastly, really. I'll pull up a test instance to see how it goes these days.

**Comment by akx** [comment]
Very sporky. If you get it to half-break again, care to paste the HTML as received from the server? I suspect some data fetches fail, or don't have the proper guarantees (see below) set.

https://github.com/City-of-Helsinki/kerrokantasi-ui/blob/496ed8677a6bcaa841d87a5f47c998695a21f0dc/src/views/QuestionView.js#L15-L43

**Comment by akx** [comment]
This seems to tie into #410. An executive decision should probably be made about how to tackle SSR. It shouldn't be impossible to use a compiled Webpack bundle as a server-side renderer either, mind...

**Comment by Rikuoja** [comment]
There's no need for this atm apart from the metadata tags, which already has issue #317 . Shouldn't need whole SSR to do that.
