### ISSUE TITLE
Create basic smoke tests for the UI

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#418]
Five tests needed, perhaps with mock API and data:

1) front page
2) hearing listing
3) hearing page
4) posting a comment
5) hearing subsection page

**Comment by Rikuoja** [comment]
There is already issue #145 about fixing tests and discussion on Jest, but we cannot fix tests if we don't have any :)

**Comment by akx** [comment]
Jest has been switched to, so that's a non-issue. :)

**Comment by jonnetanninen** [comment]
Is there more specification to this what exactly should be tested from each view?

**Comment by jussiarpalahti** [comment]
I don't know what Riku had in mind, but I'd take current kerrokantasi state (from the site) and make enzyme checks and Jest snapshots based on that.

**Comment by Rikuoja** [comment]
Current production version does work. The master branch does not :/

**Comment by Rikuoja** [comment]
Done.
