### ISSUE TITLE
Add marker gif to leaflet map dependencies in the Hearing editor Step 3 map

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#421]
Currently, the point marker is displayed as a broken image because it is not included.

**Comment by akx** [comment]
i.e. use a `require`d URL for the icon so Webpack can deal with it, like in https://github.com/PaulLeCam/react-leaflet/issues/355#issuecomment-322048544

**Comment by jonnetanninen** [comment]
With a quick glance this might actually be a problem with Leaflet and/or webpack as stated here https://github.com/Leaflet/Leaflet/issues/4968 & https://github.com/Leaflet/Leaflet/issues/4849

**Comment by Rikuoja** [comment]
Fixed.
