### ISSUE TITLE
Replace Hearing sidebar with a horizontal component

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#423]
The problem is that the Sidebar is not very visual and does not scale with a large amount of sections. Therefore, a horizontal scrollable component is needed instead.

![image](https://user-images.githubusercontent.com/9367712/31496988-1eb0a014-af66-11e7-9630-05cdd8802728.png)

The functionality could be implemented e.g. with https://github.com/akiran/react-slick in Center mode. This way, the selected section will be scrolled to the center, also when switching the section with the Next/Previous section buttons (don't know how easy this will be to implement i'm afraid :/).

Therefore, *only* the sections (including the hearing itself, i.e. the main section) should be rendered, no headlines as in the old sidebar.

**Comment by Rikuoja** [comment]
The map from the sidebar should be rendered as a thumbnail left of the main section. When clicked, it opens a larger (modal) view of just the map.

**Comment by jonnetanninen** [comment]
Am I understanding correctly that this component shouldn't scroll down with the view like the sidebar did, but instead be static at the top of the hearing view?

**Comment by Rikuoja** [comment]
Yes. Because actually the section nav, in this case, should be moved *under* the text content (but before the opinions), so the user will always get to the next section by clicking the next/previous buttons there, after reading one section through.

Therefore, there is no need to see this component if the user has scrolled down.

**Comment by Rikuoja** [comment]
So yeah, this includes moving the section navbar component too, and including this component to the main page so the user can move from the hearing main page to the first subsection by clicking a button, if subsections are present.

**Comment by Rikuoja** [comment]
Done.
