### ISSUE TITLE
Hearing editor IE11 compatibility

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#431]
Several issues were reported by the users trying to edit a Hearing with IE11. Check hearing editing, map editing, hearing creating and hearing re-editing flow on IE11 and fix any observed issues; some of them might be utterly unreproducible :/

- [x] The map editing tools were reported not to finish the geometry properly.
- [x] The map editing tools were reported not to work at all when trying to re-edit the hearing.
- [x] After a hearing was saved and previewd, the edit hearing button was reported not to work any more.
- [x] When logged out and logging in again, the hearing edit button was reported not to work any more.

Most likely these are a result of some component failing and crashing at some point, resulting in something in the state not being right anymore with repercussions down the line.

**Comment by jonnetanninen** [comment]
- [ ]  hearing address is undefined before slug input

**Comment by jonnetanninen** [comment]
Could not reproduce any of the original issues on test. My hypothesis is that those were related to other issues and are already fixed.
