### ISSUE TITLE
Hearing editor page loads but crashes in production when logged in

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#451]
Existing non-public Hearings cannot be edited.

Viewing an existing non-public Hearing, we get "Jokin meni pieleen" error. This means the page no longer works, the Edit button does nothing and the editor doesn't load.

**Comment by jonnetanninen** [comment]
Could not reproduce. Could it be that this was already fixed in some PR?

**Comment by Rikuoja** [comment]
Fixed.
