### ISSUE TITLE
When several Images are present in Section, only render the first Image of the images array at the top of the Section

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#452]
This needs to be implemented before https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/417 . This way, when several Images are posted in the editor, only the top image is rendered as the header image. 

The rest of the Images will not be rendered outside the section text html. If the user uploads images in the editor, these images will be placed within the HTML and do not need to be rendered otherwise.

**Comment by jonnetanninen** [comment]
Can't figure out what this means... :(

**Comment by Rikuoja** [comment]
This means that if the images json of a section

```

            "images": [
                {
                    "id": 96,
                    "url": "https://api.hel.fi/kerrokantasi/media/images/2016/06/kesa14_687__webiso.jpg",
                    "width": 1000,
                    "height": 667,
                    "title": {},
                    "caption": {
                        "fi": "Kuva: Lauri Rotko"
                    }
                }
            ],
```

were to contain several images (currently only one is usually present), we only render the first image. The first image is also the one that should be displayed as section thumbnail.

**Comment by Rikuoja** [comment]
So, the other images in the array should not be rendered, unless the section html specifically renders those images separately.

**Comment by Rikuoja** [comment]
Done.
