### ISSUE TITLE
In a non-public Hearing that is visible to admin, the editor bar at the bottom disappears when going to subsection views.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#456]
When entering a subsection page, the editor bar is no longer visible. Then, going back to the Hearing main page, the editor bar has disappeared.

Only reloading the page will make the editor bar visible again.

**Comment by Rikuoja** [comment]
Sadly, not fixed yet. This will be addressed in the related issue #487

**Comment by Rikuoja** [comment]
When users create a hearing and look at the created sections, they are permanently removed from the admin UI mode and have to reload or log out and in again.

Could this issue be ameliorated without too much of a refactoring, just by checking the admin status of the user also when entering the hearing from the subsections? Currently, it is only checked when the hearing route is entered, which results in the bar disappearing and not appearing again :(

**Comment by jonnetanninen** [comment]
This is actually not a bug but a feature and needs #487 to be solved before this. At the moment the hearing editor component lives inside "HearingView" and subsection are inside "QuestionView". Thus the hearing editor won't work inside QuestionView/Subsections.

**Comment by jonnetanninen** [comment]
This has was solved with PR #544
