### ISSUE TITLE
Translate instruction texts to finnish in hearing editor map

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#459]

**Comment by jonnetanninen** [comment]
What does this mean more specifically? At the moment whole hearing editor should be in Finnish.

**Comment by Rikuoja** [comment]
Ah. This seems to refer to the react-leaflet map tooltips etc.

**Comment by jonnetanninen** [comment]
Does this require action?

**Comment by Rikuoja** [comment]
Depends on whether react-leaflet is easily localizable :)

**Comment by Rikuoja** [comment]
Done
