### ISSUE TITLE
X/Close does not close hearing editor popup

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#462]

**Comment by petterill** [comment]
currently no way to cancel if already started to create a hearing

**Comment by Rikuoja** [comment]
Works for me. Which browser are you using?

**Comment by petterill** [comment]
Chrome 61.0.3163.100 on win10 enterprise

**Comment by jonnetanninen** [comment]
Can't reproduce, could this be because most of the X button was left under the navigation bar if the page was scrolled down before opening the editor?

**Comment by Rikuoja** [comment]
I managed to reproduce this. On kerrokantasi.hel.ninja, after scrolling the map around in an existing hearing, trying to close the window resulted in the minified react error
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`
```

Then, clicking another button on the editor will belatedly close the hearing.

**Comment by Rikuoja** [comment]
So could this have something to do with react-leaflet?

**Comment by jonnetanninen** [comment]
Yes, got it now. This was probably due to wrong use of <GeoJSON /> element as it was formerly used as <GeoJson />. Should be fixed in next PR.
