### ISSUE TITLE
As an official I want to be able to use old hearing as a template when creating new one.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#47]

**Comment by rambo** [comment]
What exactly does this mean ? Copying all the content (sans comments) to the newly created hearing, is there something (else) that should be left out ??

**Comment by joonasp** [comment]
yes, just leave out all end-user input (e.g. comments) and replicate just the hearing metadata that the official has inputted.

**Comment by akx** [comment]
Closed via tasks in backend project.
