### ISSUE TITLE
Add error message for user trying to upload an image that is too large

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#475]
Check the image size when added to section. Now, the user is presented with "Tarkista kirjautumisen tiedot" with no way of knowing that the reason is the image.

**Comment by jonnetanninen** [comment]
The error handling from the response is pretty awkward at the moment, would it be ok to hard code the size validations to the UI and pre-emptively notify the user if he tries to upload image that is too big?

**Comment by Rikuoja** [comment]
Definitely. Much better to validate the image before the UI even tries to send it :)

**Comment by Rikuoja** [comment]
Validating in the UI based on the API responses is another thing, would require some rewriting plus checking the backend errors for consistency.
