### ISSUE TITLE
When the user has changed data in the editor, the first click on the "Tallenna muutokset" button doesn't do anything

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#477]
For some reason, after changing a field in the form, first click on the save button doesn't work. Clicking the save button again will save the changes.

**Comment by jonnetanninen** [comment]
It seems that if input field is selected, state changes are done onBlur which then prevents the save action from being dispatched simultaneously. I think this could be solved if editor state changes happen on onChange event which should also be better functionality for the editor overall
