### ISSUE TITLE
As an official I want to be able to edit subjects (labels) of hearing, so that the residents find interesting hearings easily.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#48]

**Comment by piotras** [comment]
What is the use case to have multiple subjects (labels) per one hearing?

**Comment by Rikuoja** [comment]
They are for classification and archiving purposes, serving as tags to filter by.

**Comment by Rikuoja** [comment]
See an example in https://kerrokantasi.hel.fi/meilahdenkoulut, that one has one tag for the topic (schools) and another one for the neighborhood the discussion is about (Meilahti). More complex issues might have lots more tags for them, if they e.g. concern several topics and/or several areas. The idea is to match the tags with the City of Helsinki topic index, which is a huge database.

**Comment by rambo** [comment]
Maybe we should talk about tagging hearings, subject/topic might be understood to be the subject/title of the hearing itself.

Do we need to autocomplete tag input using the topic index ? Is there an API to faciliate that ?

**Comment by joonasp** [comment]
we coud store previously used tags and autocomplete with them the next time the user is inputting tags.

we could then also populate that list of tag words at some point (e.g. with all neighbourhood names etc), but that can be done at some later stage.
