### ISSUE TITLE
Notify user if selected URL for hearing is already in use

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#503]
Create a notification that let's the user know that the selected URL is already in use and that the system has added a numeral at the end of the URL ie. xxx-1/xxx-2/xxx-3.

**Comment by Rikuoja** [comment]
So, essentially the UI has to remember the slug the user gave, and notify the user if the slug returned by the API is different. This way, the hearing can be created right away, and the user doesn't have to manually figure out a new slug; but they still can change the slug of course if they want to.
