### ISSUE TITLE
Translate "Zoom in/Zoom out" to finnish in hearing editor map

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#506]

**Comment by petterill** [comment]
Should be Lähennä/Loitonna

**Comment by jonnetanninen** [comment]
This is unfortunately impossible due the restriction caused by the library used for zooming in and out, which is different from the ones used for the other buttons :(

**Comment by jonnetanninen** [comment]
Ok I was wrong, now implemented
