### ISSUE TITLE
Align hearing editor buttons

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#507]
![kartta](https://user-images.githubusercontent.com/6796559/34482118-c2af1a9a-efbe-11e7-96a1-3a286f7eea77.PNG)

![poistaosio](https://user-images.githubusercontent.com/6796559/34482164-05f1d93c-efbf-11e7-93cb-90c3f823e62e.PNG)

Browser: Chrome

**Comment by jonnetanninen** [comment]
Actually those buttons are not related to each other, so they shouldn't be aligned, but organized in more intuitive manner

**Comment by Rikuoja** [comment]
Fixed.
