### ISSUE TITLE
Add button for user manual in hearing editor

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#509]
Button links (for now) to https://drive.google.com/open?id=1vtUNzbJNVcp7K9JPrE6XP8yTmkBLW3N3FGEsR1NbbIw 

Button location in the admin ui should be noticeable, perhaps upper right corner (left of x-button) and colour should be light blue or whatever is a good ui convention and fits current style. Button should perhaps be a universally understood icon such as a question mark (see LinkedEvents for example https://linkedevents.hel.fi/#/help?_k=n5r4pt)

**Comment by Rikuoja** [comment]
Done
