### ISSUE TITLE
As an official I want to be able to enable editing mode when I am viewing a hearing.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#51]

**Comment by Rikuoja** [comment]
Does this editing mode allow adding and removing scenarios etc. even when the hearing is going on? There have been lots of wishes to edit hearings even after they were published.

**Comment by rambo** [comment]
I guess there is no technical problem with editing hearings even after they're opened for comments, but then we should store versions of the hearings/scenarios and comments should be linked against specific version and some sort of "this comment was given to older version of the text" note in the comment display.

**Comment by juyrjola** [comment]
Yeah, let's keep it simple. Removing sections would be a problem especially when people have commented on them. We could maybe have editing sections open (for typo corrections etc.), but disallow removing or adding them.
