### ISSUE TITLE
Add UI language selection to URL

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#510]
This will e.g. allow linking to a hearing in a specified language, if several languages are present.

Let Finnish be the default (in the absence of language selection in the URL), and Swedish or English will be specified by an extra parameter in the URL. Perhaps along the lines of kerrokantasi.hel.fi/sv/ and kerrokantasi.hel.fi/en/ ?

**Comment by jonnetanninen** [comment]
Would it be ok to implement this as a url search parameter e.g. "/hearings/list?lang=sv"?

I think this would be easiest to implement without having to refactor all the routing within the application.
