### ISSUE TITLE
As an official I want to be able to download a report about the hearing.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#52]

**Comment by rambo** [comment]
Is this the final(?) report that the official uploads or something generated by the backend from the hearing data ?

**Comment by itimo** [comment]
CSV-file with every comment on its own line + date, time, name/nick.

**Comment by juyrjola** [comment]
We found an Excel format working better for the end users, so at least XLSX exporting option should be provided. This Python package should make generating the file pretty straightforward: https://pypi.python.org/pypi/XlsxWriter
