### ISSUE TITLE
Fix: edits to hearing closing announcement are not saved

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#531]
When the user edits the default closing announcement (sulkeutumistiedote) in the hearing editor, edits are not saved even when clicking save.

**Comment by jonnetanninen** [comment]
Might be related to #523

**Comment by Rikuoja** [comment]
Or to #520

**Comment by JoonasNislin** [comment]
When creating new hearing, POST sends two sections to api that contain closing announcement but the following GET call returns only main section. Might be related to #520

**Comment by JoonasNislin** [comment]
Merged to master
