### ISSUE TITLE
Make editing existing contact persons possible

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#532]
Editing previously created tags and contact persons should be editable. Clicking the name of the tag or contact person should bring up an editor window similar to the window where the tag/person was created

**Comment by jonnetanninen** [comment]
@rikuoja does the API support this?

**Comment by Rikuoja** [comment]
Nope. Created backend issue https://github.com/City-of-Helsinki/kerrokantasi/issues/301 as a priority.

**Comment by Rikuoja** [comment]
With contact persons this should be straightforward.

However, we have the problem that labels are shared between hearings. We really don't want people to change each others labels (let along across organizations) without knowing it. People will think they are only editing the hearing in question, but all of a sudden the change is everywhere where the same label is used.

My suggestion in the backend issue is that only labels created by the same user may be edited. Then, of course, old labels may not really be edited, but I believe that is for the better.

In the long run, of course, we should transition to using yso (yleinen suomalainen ontologia) keywords and Helsinki neighborhoods as labels. This would mean the user no longer may create their own labels, but they can select the labels and the neighborhoods from a list; this is similar how yso keywords are used e.g. in linkedevents.hel.fi event creation form.

Therefore, my question is: in the meantime, do we want the users to be able to edit their own labels, even if in the long run, the labels should come from an ontology or Helsinki district list and may not be edited by users?

**Comment by jonnetanninen** [comment]
This is a quite complex feature to implement, so my recommendation is to wait for the final solution to avoid wasting too much time & money

**Comment by Rikuoja** [comment]
I agree, no sense in allowing editing of existing labels. In most cases, we don't want to allow it anyway.

Therefore, this issue henceforth only requires editing contact persons. Those will be input by hand in the future as well, and there is an existing need to edit all organization contact persons already.

**Comment by Rikuoja** [comment]
The relevant backend issue is https://github.com/City-of-Helsinki/kerrokantasi/issues/301
