### ISSUE TITLE
Fix: new tag/person fields are populated with info from previously created tag/person

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#534]
When the user creates a new tag / contact person in the hearing editor, saves and then clicks plus again, the fields in this pop up window are populated by info from the previously created tag/person. The fields should be empty by default, as they are when the user first creates a tag/person just after opening the editor.

**Comment by Rikuoja** [comment]
Related to #531 , the fields in the modal should be either empty (creating a new one) or the object that was clicked (editing an existing one).
