### ISSUE TITLE
Transition to using OpenID Connect and use silent renewal of user token

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#553]
To ensure that the user will actually stay logged in while editing the Hearing.

**Comment by Rikuoja** [comment]
This issue includes starting to use an up to date version of our SSO Tunnistamo. Therefore, an OIDC implementation is needed in place of the old OAuth that kerrokantasi-ui currently uses.

**Comment by Rikuoja** [comment]
```"oidc-client"```

**Comment by Rikuoja** [comment]
E.g. https://github.com/City-of-Helsinki/kaavapino-ui has a recent implementation, we would want it to work similarly here.

**Comment by Rikuoja** [comment]
Ah, apparently https://github.com/city-of-helsinki/helpt-ui/blob/master/src/util/user-manager.js#L9 is a simple way to do it.

It uses `redux-oidc` as well, which performs silent renewal of the token in the background, and allows us to use the OIDC Implicit Flow, where everything happens in the client side and we need no server component in the UI. (We will retain the `server.js` though for server side rendering reasons.)

**Comment by Rikuoja** [comment]
So this describes the renewal of the token with implicit flow: https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow

**Comment by farrukh8925** [comment]
well, i've spent a little time going about the process. The problem is configuration files and how we read configurations in kerrokantasi. Since everything is in ./server/getSettings (which can only be read at the time of compilation), it becomes a challenge to access those variables outside the scope of ./server/. That being said we can "inject" using DefinePlugin. But lets see, im experimenting with it, since im not that familiar with client side authentication process.

**Comment by farrukh8925** [comment]
BTW, this would mean no more `passport-helsinki`, right ?

**Comment by Rikuoja** [comment]
Yes, I believe we can get rid of `passport-helsinki` if we get OIDC authentication working.

**Comment by Jogha** [comment]
Is there any progress regarding using `redux-oidc`. For Kerrokantasi Turku case we are thinking on transitioning to that, and if there is already something done it would help us. Also is there any known problems that might arise when transitioning?

**Comment by Rikuoja** [comment]
I haven't seen any progress on this front, perhaps @farrukh8925 can tell if there is a WIP branch or something somewhere on this topic that @Jogha could continue on?

**Comment by Rikuoja** [comment]
Seems to be functioning now!
