### ISSUE TITLE
If hearing has both subsections and alternatives, their ordering in horizontal navbar & next/previous buttons does not match

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#554]
Mikko:

jos osa on vaihtoehtoja ja osa osa-alueita, niin ylänauhan ja alareunan nuolien järjestys ei vastaa toisiaan.

Helsinki Gardenin kyselyssä on viisi alakohtaa. Tein ne vaihtoehtoina, paitsi yksi meni vahingossa osa-alueena. Ylävalikon nauhassa ne näkyvät oikeassa järjestyksessä eli siinä järjestyksessä kuin tein ne. Sen sijaan kun lähtee siirtymään aloitussivulta sivun alareunassa olevalla nuolella seuraavaan vaihtoehtoon, niin tämä yksi erilainen on viimeisenä.

**Comment by Rikuoja** [comment]
Not needed, #556  will get rid of those pesky critters.
