### ISSUE TITLE
Remove option to add alternatives in hearing editor

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#556]
There is no need to have separate options to add both subsections (osa-alue) and alternatives (vaihtoehto) anymore, because these names are not shown to the user 
 browsing the hearing anymore. Remove the option to add alternatives.

**Comment by Rikuoja** [comment]
I guess `subsection` is good for everything atm.

Once we remove the field from backend, we can just remove it from the UI too.

This means the UI should work even if the backend is missing the section type field, and it should not read the field at all, but for backwards compatibility it should add `subsection` when POSTing.

**Comment by jonnetanninen** [comment]
Will main section and closure section still contain section type field? I would recommend leaving the field and giving some type for subsections (e.g. subsection), as this might be huge issue and refactoring for the UI and might potentially be a source for gazillion new bugs...

**Comment by Rikuoja** [comment]
Hm, if we cannot ignore the field I believe we may safely just assume they are all subsections. Or in the reducer, we can just add `subsection` to the type field, so everything works as before?

**Comment by Rikuoja** [comment]
Indeed, only now do I realize that we will still need the `type` for `main` and `closure-info` :D My bad. So let's keep it `subsection` for all the other sections, then.

Mind that the backend still contains old sections that have other strings there, though. I believe we should just assume `subsection` in the UI even if the backend returns a string that is something else.
