### ISSUE TITLE
Closureinfo displays html tags in plain text

### ISSUE THREAD

**Issue by jonnetanninen** [City-of-Helsinki/kerrokantasi-ui#568]
This is because before rework closure section used dangerouslySetInnerHtml and after rework it is displayed in plain text. Should be fixed by using inner html again to display old infos properly.

**Comment by Rikuoja** [comment]
When was it actually reworked to only allow plain text? Because I think the specs have always been that the closure section needs to contain links, so it cannot be plain text :)
