### ISSUE TITLE
Using marker in hearings geojson will give "Attempted to load an infinite number of tiles" error

### ISSUE THREAD

**Issue by jonnetanninen** [City-of-Helsinki/kerrokantasi-ui#569]

**Comment by Rikuoja** [comment]
Might be related to https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/519

**Comment by petterill** [comment]
When user reopens the editor, the trash can icon is active on map, and user must click delete all drawings to be able to place a geometry again. At this point it is possible to add the marker again, but saving is not possible. But when the user closes the editor, the marker appears on hearing draft map.

**Comment by jonnetanninen** [comment]
This is actually not merged yet, though there is a fix
