### ISSUE TITLE
Add option to delete hearing draft

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#580]
Would be nice to be able to delete unpublished drafts. Shouldn't be possible to delete already published hearings.

**Comment by Rikuoja** [comment]
Definitely. Created backend issue https://github.com/City-of-Helsinki/kerrokantasi/issues/302 to support draft deletion.

**Comment by Rikuoja** [comment]
Implemented in backend, ready for work.
