### ISSUE TITLE
Fix reducers so that passed arguments are not mutated

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#597]
At the moment, e.g. https://github.com/City-of-Helsinki/kerrokantasi-ui/blob/master/src/reducers/hearingEditor/hearing.js#L49 uses `merge`, which mutates the passed state instead of producing a new one, which is a big no-no: https://redux.js.org/troubleshooting#never-mutate-reducer-arguments

As this may result in all sorts of weird errors (and Redux logger being unusable debugging such state changes), reducers should be checked and fixed using e.g. `immutability-helper`.

**Comment by jonnetanninen** [comment]
Those are not actually mutated as they are destructured inside curly brackets after using merge with ES6 destructuring syntax ({...merge(obj1, obj2})) which will then return a new object
