### ISSUE TITLE
As a resident I want to see borough/location which hearing concerns in a sidebar.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#61]

**Comment by itimo** [comment]
A user-defined area/location is shown. Map will be developed with leaflet js-library. Database-model for storing areas/locations is needed.

**Comment by piotras** [comment]
Is there a use case to provide more than one location per hearing? If not, why do we need model to store locations?

**Comment by akx** [comment]
https://github.com/PaulLeCam/react-leaflet
