### ISSUE TITLE
As a user, I want to be able to see a visualization of how the hearing is related to other parts of the decision making process

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#612]
Sketches: https://sketch.cloud/s/DE904/all/user-ui/vaiheet

**Comment by Rikuoja** [comment]
The project of the hearing will be available inlined in the Hearing json; the active phase is defined by which phase of the project contains this hearing.

**Comment by Rikuoja** [comment]
Alternative placing for the phases: https://sketch.cloud/s/DE904/all/user-ui/vaiheet-placement-alternative
