### ISSUE TITLE
Display language version fields in fixed order in hearing editor

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#615]
Default ordering is fin-swe-eng when first creating the draft but afer saving the draft the order changes. Applies to all fields in editor. See image:

![kk-isuue-lang-editor](https://user-images.githubusercontent.com/6796559/36907309-0410c8d4-1e41-11e8-933e-cd546087d125.PNG)

**Comment by akx** [comment]
Sounds like there's no particular order set for them.

**Comment by Rikuoja** [comment]
Yeah, most likely this is a feature (not a bug), but an order might be specified if that's needed.

**Comment by petterill** [comment]
Ok I renamed this. Probably confusing to the user if the ordering changes randomly.

**Comment by Rikuoja** [comment]
Looks like the order is alphabetical now.
