### ISSUE TITLE
Allow editing POSTed answer

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#646]
Currently, if a registered user has POSTed answers to questions, they may no longer be edited. While the comment in the comment list may be edited, the answers may not.

Therefore, allow user to edit their answer along with the comment in the list.

**Comment by Rikuoja** [comment]
Implemented in #686 , but two problems remain:
1) in the frontend, a selected multiple-choice answer is deselected when clicking another field in the form,
2) in the backend, some answers disappear after editing them.

**Comment by Rikuoja** [comment]
https://github.com/City-of-Helsinki/kerrokantasi/commit/2e58341798b25d3744df89fd57686ab67f360d8f should fix the backend issue.

The frontend deselection bug of the checkbox remains.

**Comment by JoonasNislin** [comment]
Seems like this is already fixed, cant reproduce
