### ISSUE TITLE
Allow user to answer comments (nested comments)

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/kerrokantasi-ui#674]
The user should be able to answer a specific comment, instead of answering the whole hearing.  This function is achieved by adding a text link called "Vastaa" (eng. answer, sw. svara) under each comment. After the user clicks "Vastaa", the new comment form should open below the comment, which the user is replying to.  Answers to a comment should appear nested below the original comment. The UI design is presented in the following picture: [nestedcomments2](https://user-images.githubusercontent.com/39044068/58322475-beb80280-7e29-11e9-90d2-de690072f29d.jpg)

**Comment by farrukh8925** [comment]
So, we only allow a single nested reply ? 
question { answer }

and not 

question ( answer { another answer { another question and so forth } } )

**Comment by katjahenttonen** [comment]
The UI of #674 should be implemented according to the picture.  Each comment has a  "Vastaa" link so, yes, one can also reply to "a comment of a comment" etc.  But visually, only the first answer should be indended (all other answers are on the same level). I guess the UI designer just though that indending each answer would look a mess on screen if there is long discussion.

**Comment by Rikuoja** [comment]
Okay; so should the comment still contain data which one of the answers the user is answering? E.g. there seems to be "Vastauksena käyttäjälle Anonyymi" in one of the answers. What comment does that answer to, to the top comment or one of the comments below? Or do we need that text at all, probably not?

**Comment by Rikuoja** [comment]
Also, if somebody comments and answer in the middle, is the answer still shown at the end of the answer list?

**Comment by katjahenttonen** [comment]
Thank for @Rikuoja you clarifying questions. Unless it is technically very difficult to implement,  I suggest we follow the UI designers plan and include "Vastauksena käyttäjälle [nickname]" in the answers.  The text is apparently there to replace indent as a manner of communicating  to whom the user is replying. There is a "Vastaa" link included in each comment and therefore the user can unambiguously identify which comments s/he wants to reply. So in "Vastauksena käyttäjälle [nickname]",  nickname is the author of the comment whose "Vastaa" link was pressed by the user.  As to your second question, I think the answer to the comment should be in the middle, below the original comment answered.

**Comment by Rikuoja** [comment]
Okay, so this would mean a more complex data structure in which there could be a comment tree of any depth in the backend. A comment could have any number of subcomments, and their subcomments, and there would have to be lots of fetches of each new layer of subcomments, or then inlined stuff in the JSON.

I would recommend against it, e.g. in Facebook they have realized such a structure is too complex, and all comment answers are answers to the original comment, even if they contain a reference to the author of another subcomment. Also, the new comment is always on the bottom of the subcomment chain, not in the middle. It makes subdiscussions simpler to implement and easier to follow when new comments are added.

In any case, API support is needed for the subcomments. I am in the process of implementing simple subcomments, but if we need several layers of subcomments, also the API work will surely become more complex.

**Comment by Rikuoja** [comment]
The simpler variant (as seen on facebook) is that initially, only the original comments are displayed.

Then, when the user clicks on a subcomment thread, subcomments (either latest or first of them) are loaded. The user may click a link in the subcomment thread to load more subcomments.

This whole logic, i.e. which comments are shown initially, and how more comments are loaded, is not considered in the pictures.

**Comment by Rikuoja** [comment]
We must remember that there can be hundreds of comments. There is no way we want to load or display all of them at once, and it would make scrolling to see the original comments very slow.

**Comment by Rikuoja** [comment]
I assume the "Näytä lisää" button in the first comment in the picture is meant to load the subcomments?

**Comment by Rikuoja** [comment]
In that case, it would be very beneficial to show (like on facebook) how many subcomments a comment has, so the user knows if they want to click and start loading them.

**Comment by katjahenttonen** [comment]
Based on the feedback from @Rikuoja, we have changed to design of nested comments slighly. @farrukh8925  please find the new design depicted in  enclosed pictures.  For each thread, only the first answer is shown by default. To see all the rest of the replies, the user can then press the link that says "Lataa lisää vastauksia +number of replies in paranthesis".  Once the thread is open, there should be an equavalent link to close it e.g. "Näytä vähemmän vastauksia" (ignore wrong font in the word "vähemmän"). 
![nestedcomments-open-thread](https://user-images.githubusercontent.com/39044068/58802702-81682780-8616-11e9-9f57-b24c71ac4c57.png)
![nested-comment-thread-closed](https://user-images.githubusercontent.com/39044068/58802711-84631800-8616-11e9-8216-8b5381f9a73e.png).  

I will update related issues accordingly.

**Comment by katjahenttonen** [comment]
From #675  "the comment form should open in the middle of the thread when the user clicks "Vastaa". However, the newly added comment should be placed at the end of thread and the screen should be scrolled down so that the user sees the comment she/he added.

**Comment by farrukh8925** [comment]
@katjahenttonen while design part is ready, i cant start with it until i can create an actual nested comment :(

**Comment by Rikuoja** [comment]
API support should be there now :)

**Comment by katjahenttonen** [comment]
Please find below UI design on how the reply form should show up in the thread (apologies for forgetting to attach this earlier).  The pics shows the admin comment form but obviously the ordinary comment from should show up in the similar manner.
![replytocomment](https://user-images.githubusercontent.com/39044068/59087888-a3132880-890e-11e9-95ea-c81980f6d7ce.png)

**Comment by Rikuoja** [comment]
Solved in #682
