### ISSUE TITLE
Highlight comments by admins with yellow heading

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/kerrokantasi-ui#676]
When a KerroKantasi admin user leaves comments (with a slightly different comment form defined in #675), the comments should be highlighted with a yellow heading.  As shown in the attached picture, the heading contains a fixed text "Helsingin kaupungin työntekijä:",  the name of the employee,  the date of the comment and the unit of the employee.  
![kaupunginvastaus](https://user-images.githubusercontent.com/39044068/58422941-89671b00-809c-11e9-8ce7-59377a8da912.png) Please ignore wrong font in "Kaupungin vastaus".

**Comment by katjahenttonen** [comment]
The design has slightly changed here, please see the new pictures enclosed. 
![city-employee-comment-to-hearing](https://user-images.githubusercontent.com/39044068/58804388-6bf4fc80-861a-11e9-958b-0778d95600bf.png)
![nestedcomments-open-thread](https://user-images.githubusercontent.com/39044068/58804433-88913480-861a-11e9-87d3-ff34b9f0e7cc.png)

**Comment by Rikuoja** [comment]
Here, we will display the yellow bar if comment `organization` is not null. Best just display the name of the organization as it is read from the comment `organization` field directly.

**Comment by Rikuoja** [comment]
Now the `organization` in the comment JSON should display the name of the author organization, so you can just display it here.

**Comment by farrukh8925** [comment]
@katjahenttonen there is are 2 minor issues. One, the color is not available in style guide, the closest is ``#ffe977`` named ``engel``
second, there will be some visible offset to the admin comment to the left to acomodate the border. in the snapshots you provided, perticularly the second one, the border is out of bounds of the parent div.

**Comment by farrukh8925** [comment]
@Rikuoja i also noticed that when posting a new comment, the default behaviour is that the comment is stacked to top and list is re ordered ignoring the filters. That is too causing the jumping after one comment as a sub comment.

**Comment by katjahenttonen** [comment]
@farrukh8925  i apologize for a late comment, but please you the same shade of yellow as in the UI specs, i.e. R: 255 G: 247 B: 175.

**Comment by Rikuoja** [comment]
Solved in #682
