### ISSUE TITLE
Pinned comments

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/kerrokantasi-ui#679]
KerroKantasi admin users (ie. users who are able to open new hearing) should be able to "pin" their comments so that their always appear on the top of the list.  Please see the picture of the pinned comment enclosed. The pinning should happen by pressing a small "pin" icon, which is next to the thumbnail icon.  When the comment has been pinned, there should also be icon for unpinning it (missing from the picture).  

![city-employee-pinned-comment](https://user-images.githubusercontent.com/39044068/58806715-6f3eb700-861f-11e9-9450-7161db45e084.png)

**Comment by katjahenttonen** [comment]
Please find the pin and unpin icons below:
![push-pin](https://user-images.githubusercontent.com/39044068/58809052-dc544b80-8623-11e9-94fb-9c3d7043be7f.png)
![cancel-push-pin](https://user-images.githubusercontent.com/39044068/58809037-d6f70100-8623-11e9-923a-d0600fcb223a.png)


![push-pin](https://user-images.githubusercontent.com/39044068/58809015-ca72a880-8623-11e9-9d45-b88a9499ac53.png)

**Comment by Rikuoja** [comment]
I suggest we use the existing comment PUT functionality. This will just require a new comment API field `pinned`, that will be `False` by default, and may only be set by admins in the backend.

**Comment by katjahenttonen** [comment]
@Rikuoja  This is probably a silly question, but what do you mean "may only be set by admins in the backend"?  I hope that refers to how backend handles the API call ... not that pinning must be done by me from the admin panel.  :)   Anyways, the pin and unpin icons should only be visible for admin users in  the UI.

**Comment by Rikuoja** [comment]
Yeah, I mean indeed any of the admin users in the UI, not you in the backend :)

**Comment by Rikuoja** [comment]
Okay, now the backend supports giving `pinned: True` in the comment json, and filtering by `?pinned=true` and `pinned=false` to get the pinned comments to the top!

**Comment by farrukh8925** [comment]
@katjahenttonen is it possible to get the svg's for the icons ? And also, the icons will go above the "thumbs up" icon ?

**Comment by Rikuoja** [comment]
Perhaps we should allow pinning the comment in the comment form when first writing them? Then, we wouldn't have to first POST the comment and then PUT it again when the user finds their comment?

**Comment by farrukh8925** [comment]
Possible, something subtle though. As the comments already have a lot going in them.

![sample](https://user-images.githubusercontent.com/49946648/59342401-63837c80-8d12-11e9-91c9-cae663e42ee0.png)

**Comment by katjahenttonen** [comment]
@farrukh8925 and @Rikuoja  sorry for late reply again.
- thank you  Farruck, I like the way you embedded pin icon into the comment form.  It can indeed be subtle because only a  small number of admin users use pinned publications for specific purpose.
- I will attach SVG icons ASAP.

**Comment by Rikuoja** [comment]
Solved in #700
