### ISSUE TITLE
As a resident I want to see five (5) newest hearings and hearing reports at front page.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#7]

**Comment by itimo** [comment]
"Add newer hearings and hearing reports" directs to hearings -page.

**Comment by rambo** [comment]
Is this related to #8, if so, how ?

**Comment by akx** [comment]
@itimo: What are "hearing reports"? The front page currently lists the 5 newest hearings alright.

**Comment by juyrjola** [comment]
@akx: Hearing reports are the human-generated summaries of the hearing comments. This is outside the scope of MVP.
