### ISSUE TITLE
As a resident I want to be able to sort the comments any order I see fit.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#74]

**Comment by rambo** [comment]
The users might come up with the weirdest sorting criteria, we should nail this down to a few options like

  - date created,
  - number of upvotes
  - If the comments have separate subject/title field alphabetically with that ? (not sure how useful that actually would be but hey...)

And ascending/descending to each.

Additionally a checkbox for thread-style view would be nice where replies are shown under the comment they reply to.

**Comment by Rikuoja** [comment]
Done. No comment threads yet tho.
