### ISSUE TITLE
Prevent total data loss in hearing editor whenever something goes wrong

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#742]
Currently, the UI has a potential of significant data loss on the user's part, if the user is not careful and does not manually 1) log in again regularly and 2) press save button (and actually verify the button press and save has gone through) regularly.

Steps to reproduce:
1) Log in and start happily editing a draft hearing (or creating a new one)
2) Press save every now and then, but do not repeat presses. In this case, first press of the save actually just does `blur` but does not send any data to the API.
3) Happily add a few dozen sections with images and everything.

By this point, either the login has gone old (token is no longer valid, though the user and the UI think it is still OK), or some of the data is not valid (some required field among dozens is missing), or most likely both.

4) Attempt to save the results in the end by repeatedly pressing save. Then, the user is met with error with validation, or with an outdated token, or both.

5) Possibly attempt to remediate the situation by trying to log out and in again. This requires closing the hearing editor.
6) If the hearing in question was non-public, as hearing drafts usually are, logging out triggers reload of the hearing page, which empties the editor totally. (If the hearing was public, this succeeds.)

Editor contents lost.

**Comment by Rikuoja** [comment]
Easily fixable parts:

1) automatic renewal of user token to prevent logouts, https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/553
2) do *not* empty editor state ever, even if you navigate to a different page or the page is empty?

More difficult to fix:
3) actually displaying validation messages in the right place
4) actually separating edit actions to separate PUTs, so updates to the server would be done constantly. This is the preferred (and most laborious to implement) way: https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/596

**Comment by JoonasNislin** [comment]
This has been fixed with oidc silent-renew that refreshes the user login token.
