### ISSUE TITLE
As a resident I want to be able to "vote" (thumb up) other people's comments.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#75]

**Comment by rambo** [comment]
Only logged in users may vote (to prevent vote stuffing). remember that adding comments is allowed without registration/logging in.

**Comment by piotras** [comment]
Should we record who gave vote? Or just add vote without "owner"? In other words, do we need 'who voted' functionality?

**Comment by rambo** [comment]
We need to make sure an user only votes once but probably do not want to list who actually gave thumbs up to specific comment.
