### ISSUE TITLE
Add informative cookiebar to let users know if cookies are used on the site.

### ISSUE THREAD

**Issue by SanttuA** [City-of-Helsinki/kerrokantasi-ui#755]
[Evästeistä informoiminen ja suostumus_käytännön ohjeita ja malleja_122020.pptx](https://github.com/City-of-Helsinki/kerrokantasi-ui/files/6355889/Evasteista.informoiminen.ja.suostumus_kaytannon.ohjeita.ja.malleja_122020.pptx)

**Comment by JoonasNislin** [comment]
Merged to master
