### ISSUE TITLE
Bug: file extension missing from downloable Excel file

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#776]
Users can download a summary of comments into an Excel file (see the small link "Lataa yhteenveto kommenteista Excel-muodossa" just above the blue box where people leave their comments).  Currently, this Excel-file does not have file extension and many users found that their Windows OS cannot recognize the file type.  I have to advice users to rename the downloaded file and add "xlsx" extension into its- after that all users have been able open the file without problems.  Obviously, this additional step should not be required.

**Comment by JoonasNislin** [comment]
This has been fixed in this commit dev@edb90542
