### ISSUE TITLE
Ensure that lang-attributes work in all situations

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#778]
Sivuston kieliversioihin on määritetty kieltä vastaavat lang-kielimääritykset, mutta ne eivät toimi asianmukaisella tavalla Chrome-selaimella ja NVDA-ruudunlukuohjelmalla sivustoa käytettäessä. Kielen vaihtamisen jälkeen ruudunlukuohjelman kieli ei vaihdu sivuston kieltä vastaavaksi, vaan sivu pitää päivittää selaimella käsin, jotta uusi lang-attribuutin arvo välittyy ruudunlukuohjelmalle. Ongelmaa ei havaittu Firefox-selain ja NVDA-ruudunlukuohjelma -yhdistelmällä tai mobiililaitteella sivustoa testatessa.

Korjausehdotus:

Varmistetaan, että kielten lang-attribuutit toimivat oikein kaikissa ti-lanteissa.

**Comment by JoonasNislin** [comment]
This was fixed in #777
