### ISSUE TITLE
Update link text from "Tell us..." to "Tell us by email..."

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#781]
Sivustolla on tekstilinkki, jonka kautta voi antaa palautetta palvelusta. Linkki avaa varoittamatta sähköpostisovelluksen uuteen ikkunaan. Tämä voi aiheuttaa haasteita navigaatiossa, jos käyttäjä tiedä sivun selausrakennetta ja hänet ohjataan varoittamatta täysin uudelle sivulle tai uuteen ikkunaan.  Linkin "Kerro meille miten tätä palvelua pitäisi kehittää" tekstiksi vaihdetaan "Kerro meille sähköpostitse miten tätä palvelua pitäisi kehittää".  Linkin nimi pitää vaihtaa kaikissa kieliversiossa, eng. "Please give us feedback by email...", ruotsiksi "Berätta för oss via e-post..."

**Comment by JoonasNislin** [comment]
Merged to master
