### ISSUE TITLE
In mobile version, "area-expanded" attribute and better alt-text must be added to toggle navigation button

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#783]
Sivuston mobiiliversion valikko on kuvattu ruudunlukuohjelmia varten nimellä ”Toggle navigation”. Valikkopainikkeesta ei välity ruudunlukuohjelmalle tietoa siitä, mikä valikon tila on. Näin ollen näkövammaisen henkilön voi olla vaikea selvittää, onko valikko auki vai kiinni. Käyttäjä joutuu selaamaan sivustoa, jotta hän saa selvitettyä tilanteen.
**Korjausehdotus**
Interaktiivisista elementeistä tulee välittyä avustavalle teknologialle kolme eri arvoa: nimi, rooli ja arvo. Valikkopainikkeen arvotieto (avattu / suljettu) ei tällä hetkellä välity. Ongelman korjaamiseksi valikkopainikkeeseen tulee lisätä ”aria-expanded”-attribuutti. Lisäksi valikkopainike tulee nimetä selvemmällä kuvauksella avustavaa teknologiaa varten, jotta se on paremmin tunnistettavissa navigaatiovalikoksi.  Valikkopainikkeen nimeksi tulee laittaa "Päävalikko",  englanniksi "Main menu", ruotsiksi "Huvudmeny"

**Comment by JoonasNislin** [comment]
Merged to master
