### ISSUE TITLE
Alt-text must be added to the loggin button in mobile version

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#784]
Sisäänkirjautumispainike nimeämätön mobiilinäkymässä
Kuvaus ja vaikutus
Palveluun sisään kirjautuminen tehdään painikkeesta, joka tulee sivun kielivalikon jälkeen. Kirjautumispainikkeelta puuttuu kokonaan nimitieto avustavaa teknologiaa varten sivuston mobiilinäkymässä. Tämä vaikeuttaa esimerkiksi näkövammaisten ruudunlukuohjelmaa tarvitsevien henkilöiden palvelun käyttöä. Käyttäjä ei saa selville painikkeen tarkoitusta ruudunlukuohjelman antaman tiedon perusteella. Ainut tapa selvittää painikkeen tarkoitus on kokeilemalla.
Korjausehdotus
Painikkeelle tulee antaa tekninen nimitieto sopivaa attribuuttia, kuten ”aria-label”, käyttäen.  Sopiva alt-teksti lienee "Sisäänkirjautuminen", englanniksi "Login", ruotsiksi "Logga in".

**Comment by JoonasNislin** [comment]
Merged to master
