### ISSUE TITLE
Clicking key word links should move focus to the beginning of the All hearings -page

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#785]
Selainkohdistus ei siirry sivun alkuun avainsanalinkin painamisen jälkeen
Kuvaus ja vaikutus
Sivustolla olevat kuulemiset sisältävät avainsanoja, joista klikkaamalla siirrytään Kaikki kuulemiset -sivulle, jossa näytetään kyseiseen avainsanaan liittyvät kuulemiset. Sivulle tultaessa selainkohdistus ei siirry sivun alkuun, vaan se on Hae aiheista -kohdassa, jossa on valittuna äsken klikattu avainsana. Ongelma on mainittu jo Annanpuran tekemässä saavutettavuustestausraportissa ja ongelmaa on myös korjattu siten, että kohdistus siirtyy aina samaan kohtaan.
Kun kohdistus on keskellä sivua, vaikeuttaa tilanne näkövammaisten ruudunlukuohjelmaa tarvitsevien käyttäjien sivuston käyttämistä. Nykytilanteessa oman sijainnin paikallistaminen ja sivustolla navigointi voivat vaikeutua.
**Korjausehdotus**
Selainkohdistus olisi selauslogiikan kannalta hyvä siirtää sivun alkuun.

**Comment by JoonasNislin** [comment]
Merged to master
