### ISSUE TITLE
Change keyboard focus and OK button in Write comment -form

### ISSUE THREAD

**Issue by kmhentto** [City-of-Helsinki/kerrokantasi-ui#786]
Kuvaus ja vaikutus
Kuulemisten kommenttilomakkeessa on muutamia vähäisempiä saavutettavuusongelmia.
Kuulemisten yhteydessä oleva hyppylinkki ”Kirjoita kommentti” siirtää näkymän kommentteihin, mutta ei siirrä näppäimistökohdistusta. Tämä hankaloittaa selaamista, koska käyttäjä joutuu hyppylinkistä huolimatta selaamaan koko kuulemisen läpi jättääkseen kommentin.
Lomakkeessa itsessään, sekä kommentin jättämiseen tarkoitetulla tekstikentällä että nimimerkin syöttökentällä on puutteellinen kuvaus. Kommentin kuvaus on ”muokattava monirivinen” ja nimimerkin kuvaus on ”muokattava anonyymi”.
Kommentin lähetyksen jälkeen ilmenevä ponnahdusikkuna siirtää kohdistuksen suoraan OK-painikkeeseen, lukematta viestiä onnistuneesti lähetetystä palautteesta. Tämä voi aiheuttaa sekaannusta käyttäjälle, joka ei tiedä mistä OK-painike tuli, mihin se vie ja jätettiinkö kommentti onnistuneesti. Hän voi selvittää tämän selaamalla ylöspäin mutta selausjärjestys on siinä tapauksessa epäselvä. OK-painikkeella on myös kaksi ilmentymää ruudunlukijalle. Jos painikkeen kohdalla painaa alaspäin-nuolinäppäintä, ruudunlukija ilmoittaa jälleen ”painike OK” mutta aktivoitaessa Enter-näppäimellä ei ta-pahdu mitään. Tämän jälkeen painamalla ylös-nuolinäppäintä, ruudunlukija ilmoittaa jälleen ”painike OK”, mutta aktivoiminen Enter-näppäimellä toimiikin tässä kohtaa.
**Korjausehdotus**
Hyppylinkin tulisi siirtää sekä näkymä että kohdistus alla olevaan kommenttilomakkeeseen. Kommenttilomakkeen määreisiin tulisi lisätä joko erillinen title=””-määre, tai käyttää aria-labelledby-määrettä ja yhdistää se kentän yllä olevaan kuvaustekstiin.
Ponnahdusikkunan tulisi kohdistaa ensin viestiin hyväksytyn kommentin lähettämisestä, sen jälkeen OK-painikkeeseen. OK-painikkeen tulisi myös ilmestyä vain kerran lomakkeessa ja sen tulisi viedä lomakkeesta pois aktivoitaessa.

**Comment by JoonasNislin** [comment]
Merged to master
