### ISSUE TITLE
Use Swedish map tiles in Swedish UI and English in English UI

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi-ui#797]
The map tile server allows specifying tile language by language code:

https://tiles.hel.ninja/styles/hel-osm-bright/13/4663/2370@2x@fi.png
https://tiles.hel.ninja/styles/hel-osm-bright/13/4663/2370@2x@sv.png
https://tiles.hel.ninja/styles/hel-osm-bright/13/4663/2370@2x@en.png
https://tiles.hel.ninja/styles/hel-osm-bright/13/4663/2370@2x@ru.png

So the map tile URL could change based on UI language.

**Comment by JoonasNislin** [comment]
Merged to master
