### ISSUE TITLE
As a resident I want to be able to filter the list of hearings.

### ISSUE THREAD

**Issue by itimo** [City-of-Helsinki/kerrokantasi-ui#80]
Possible filters:
- no filter
- status = open
- status = closed
- year and month

What other filters would be usefull?

**Comment by piotras** [comment]
What date refers to? Creation date? Closed date? Date when hearing has been processed?

**Comment by Rikuoja** [comment]
Filtering by tags or tag types might be useful. For example, hearings on schools. Or hearings on a specific area, etc.

**Comment by piotras** [comment]
Related #10, #11, #12.

**Comment by Rikuoja** [comment]
Done.
